services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    dns:
      - 8.8.8.8
      - 1.1.1.1

  frontend:
    platform: linux/amd64          
    build: ./frontend
    command: ["npm", "run", "preview", "--", "--port", "4173", "--host"]
    depends_on:
      - backend
    ports:
      - "4173:4173"
